// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GoodbyeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodbyeRequest) Reset()         { *m = GoodbyeRequest{} }
func (m *GoodbyeRequest) String() string { return proto.CompactTextString(m) }
func (*GoodbyeRequest) ProtoMessage()    {}
func (*GoodbyeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{2}
}

func (m *GoodbyeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodbyeRequest.Unmarshal(m, b)
}
func (m *GoodbyeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodbyeRequest.Marshal(b, m, deterministic)
}
func (m *GoodbyeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodbyeRequest.Merge(m, src)
}
func (m *GoodbyeRequest) XXX_Size() int {
	return xxx_messageInfo_GoodbyeRequest.Size(m)
}
func (m *GoodbyeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodbyeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoodbyeRequest proto.InternalMessageInfo

func (m *GoodbyeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GoodbyeResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Farewell             bool     `protobuf:"varint,2,opt,name=farewell,proto3" json:"farewell,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodbyeResponse) Reset()         { *m = GoodbyeResponse{} }
func (m *GoodbyeResponse) String() string { return proto.CompactTextString(m) }
func (*GoodbyeResponse) ProtoMessage()    {}
func (*GoodbyeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{3}
}

func (m *GoodbyeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodbyeResponse.Unmarshal(m, b)
}
func (m *GoodbyeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodbyeResponse.Marshal(b, m, deterministic)
}
func (m *GoodbyeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodbyeResponse.Merge(m, src)
}
func (m *GoodbyeResponse) XXX_Size() int {
	return xxx_messageInfo_GoodbyeResponse.Size(m)
}
func (m *GoodbyeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodbyeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoodbyeResponse proto.InternalMessageInfo

func (m *GoodbyeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GoodbyeResponse) GetFarewell() bool {
	if m != nil {
		return m.Farewell
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "intelproto.Request")
	proto.RegisterType((*Response)(nil), "intelproto.Response")
	proto.RegisterType((*GoodbyeRequest)(nil), "intelproto.GoodbyeRequest")
	proto.RegisterType((*GoodbyeResponse)(nil), "intelproto.GoodbyeResponse")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca, 0xcc, 0x2b, 0x49, 0xcd,
	0x01, 0xb3, 0x95, 0x64, 0xb9, 0xd8, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8,
	0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x19,
	0x2e, 0x8e, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2,
	0x74, 0xa8, 0x34, 0x88, 0xa9, 0xa4, 0xc2, 0xc5, 0xe7, 0x9e, 0x9f, 0x9f, 0x92, 0x54, 0x99, 0x8a,
	0xcf, 0x0c, 0x7b, 0x2e, 0x7e, 0xb8, 0x2a, 0x5c, 0x46, 0x09, 0x49, 0x71, 0x71, 0xa4, 0x25, 0x16,
	0xa5, 0x96, 0xa7, 0xe6, 0xe4, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x04, 0xc1, 0xf9, 0x46, 0xad,
	0x8c, 0x5c, 0xec, 0xee, 0x10, 0x1f, 0x08, 0x99, 0x70, 0xb1, 0x7a, 0xa4, 0xe6, 0xe4, 0xe4, 0x0b,
	0x09, 0xeb, 0x21, 0x7c, 0xa1, 0x07, 0xb5, 0x5e, 0x4a, 0x04, 0x55, 0x10, 0x62, 0x9b, 0x12, 0x83,
	0x90, 0x0b, 0x17, 0x3b, 0xd4, 0x09, 0x42, 0x52, 0xc8, 0x4a, 0x50, 0x5d, 0x2f, 0x25, 0x8d, 0x55,
	0x0e, 0x66, 0x8a, 0x13, 0x47, 0x14, 0x9b, 0x3e, 0x58, 0x2e, 0x89, 0x0d, 0x4c, 0x19, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x59, 0x83, 0x9c, 0x52, 0x59, 0x01, 0x00, 0x00,
}
